version: "3.9"

services:
  almond:
    build:
      context: .
      dockerfile: Dockerfile
    image: konotorii/almond
    container_name: almond
    restart: always
    ports:
      - 3030:3030
    environment:
    env_file:
      - .env
